# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update && apt-get upgrade && \
    apt-get install -y vim curl && \
    curl -fsSL https://get.docker.com | bash && \
    usermod -aG docker vagrant && \
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && \
    cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
    deb https://apt.kubernetes.io/ kubernetes-xenial main
    EOF && \
    apt-get update && apt-get install -y kubelet kubeadm kubectl
   SHELL

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "master01"
    master.vm.network "private_network", ip: "192.168.150.10"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "master"
    end
  end

  config.vm.define "node01" do |node|
    node.vm.box = "ubuntu/bionic64"
    node.vm.hostname = "node01"
    node.vm.network "private_network", ip: "192.168.150.11"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "node01"
    end
 end

  config.vm.define "node02" do |node|
    node.vm.box = "ubuntu/bionic64"
    node.vm.hostname = "node02"
    node.vm.network "private_network", ip: "192.168.150.12"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "node02"
    end
  end
end
